language: php

cache:
  directories:
    - "$HOME/.composer/cache"

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: hhvm-3.15
    - php: hhvm-nightly

before_install:
  - 'mkdir bin'
  - 'mkdir -p build/logs'
  - travis_retry bash -c 'curl -sS https://getcomposer.org/installer | php -- --install-dir=bin'
  - bash -c 'chmod +x bin/composer.phar'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpunit.xml; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpunit.hhvm.xml phpunit.xml; fi;'

install:
  - travis_retry ./bin/composer.phar install -o --no-interaction --prefer-source --ignore-platform-reqs

before_script:
  - |
    if [[ $TRAVIS_PHP_VERSION = "hhv"* ]]; then
      echo "" >> /etc/hhvm/php.ini
      echo "hhvm.php7.all = true" >> /etc/hhvm/php.ini
      echo "" >> /etc/hhvm/php.ini
    fi;

script:
  - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
   - travis_retry bash -c 'wget --output-document=build/bin/ocular.phar https://scrutinizer-ci.com/ocular.phar'
   - travis_retry bash -c 'php ./build/bin/ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml'
